#!/bin/bash

dotfiles="bashrc tmux.conf vimrc gitconfig"

for f in $dotfiles; do
    if [ -f $HOME/.$f ]; then
        if [ ! -d $HOME/old-dotfiles ]; then
            mkdir $HOME/old-dotfiles
        fi
        mv $HOME/.$f $HOME/old-dotfiles
    fi
    ln -s ~/dotfiles/$f ~/.$f
done
