set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
" Nerdtree
Plugin 'scrooloose/nerdtree'
" Git
Plugin 'tpope/vim-fugitive'
" Markdown
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
" Haskell
" Python
" JavaScript
" TypeScript
Plugin 'leafgarland/typescript-vim'
Plugin 'Shougo/vimproc.vim'
Plugin 'Quramy/tsuquyomi'
call vundle#end()
filetype plugin indent on
syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set number
