#!/bin/bash

# ASSUMED: bash, tmux, vim, git, python

if [ "$1" == "update" ]; then
    sudo apt-get -y update
    sudo apt-get -y upgrade

elif [ "$1" == "install" ]; then
    case "$2" in
        "base")
            # upgrade to zsh and pretty colors?
            git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
            ;;
        "haskell")
            # change this to ghc and cabal, stack?
            sudo apt-get -y install haskell-platform
            cabal update
            cabal install cabal-install
            ;;
        "python")
            # upgrade to python 3 eventually
            sudo apt-get -y install python-virtualenv
            ;;
        "r")
            sudo apt-get -y install r-base
            ;;
        "latex")
            sudo apt-get -y install texlive-latex-base xzdec
            tlmgr init-usertree
            tlmgr install titlesec
            ;;
        "node")
            sudo apt-get -y install mongodb
            wget -qO- https://raw.github.com/creationix/nvm/master/install.sh | sh
            nvm install 0.10.33
            nvm alias default 0.10.33
            npm install -g express-generator
            ;;
        "")
            echo "Please Choose An Available Stack:"
            echo "base"
            echo "haskell"
            echo "python"
            echo "r"
            echo "latex"
            echo "node"
            ;;
    esac

else
    echo "Please Provide A Command"
fi
