#!/bin/bash

if [ "$1" == "install" ]; then
    case "$2" in
        "base")
            sudo apt-get -y install vim
            git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
            ;;
        "node")
            sudo apt-get -y install mongodb
            wget -qO- https://raw.github.com/creationix/nvm/master/install.sh | sh
            nvm install 0.10.33
            nvm alias default 0.10.33
            npm install -g express-generator
            ;;
        "r")
            sudo apt-get -y install r-base
            ;;
        "latex")
            sudo apt-get -y install texlive-latex-base
            ;;
        "haskell")
            sudo apt-get -y install haskell-platform
            ;;
        "")
            echo "Please Choose An Available Stack:"
            echo "base"
            echo "node"
            echo "r"
            echo "latex"
            echo "haskell"
            ;;
    esac

elif [ "$1" == "update" ]; then
    sudo apt-get update
    sudo apt-get upgrade

else
    echo "Please Provide A Command"
fi
